133 oci provider assumes the network interfaces are named
oracle-cne/ocne pull request #161
Opened 2024-11-08 00:58 UTC by zabdulre

1. Include A2 shape as a supported ARM shape
2. Remove default interfaces for oci driver.

These changes were tested by using ocne cluster template and ocne cluster create. First, a cluster was created successfully on VM.Standard.E4.Flex and VM.Standard.A1.Flex machines. The same cluster configuration was then used to create a VM.Standard.E5.Flex based cluster, and a VM.Standard.A2.Flex based cluster. All pods and nodes reached ready state in testing.

2024-11-08 11:09 UTC, mgianatagh commented on pkg/cluster/driver/capi/capi.go
>  	// ens3 is the default OCI vNIC name for x86
This comment seems out of date now.

2024-11-15 18:30 UTC, mgianatagh approved these changes

2024-11-18 16:56 UTC, dkrasins requested changes

2024-11-18 18:41 UTC, zabdulre commented on pkg/cluster/driver/capi/capi.go
> +	if strings.TrimPrefix(clusterConfig.KubeVersion, "v") == "1.26" && (clusterConfig.Providers.Oci.ControlPlaneShape.Shape == constants.OciVmStandardA1Flex || clusterConfig.Providers.Oci.ControlPlaneSh
done

2024-11-18 19:38 UTC, dkrasins approved these changes

2024-11-18 20:15 UTC, mgianatagh approved these changes

2024-11-18 20:16 UTC, merged